import Mathlib

open Fintype Subgroup Set Polynomial Ideal
open scoped BigOperators



```lean
theorem inverse_of_element {G : Type*} [Group G] (x : G) (n : ℕ) (h : x ^ n = 1) : x⁻¹ = x^(n-1) :=
begin
  have h1 : x * x^(n-1) = x^n, by rw [←pow_succ, nat.sub_add_cancel (nat.one_le_of_lt (nat.pos_of_ne_zero (ne_of_gt (nat.pos_of_ne_zero (ne_of_lt (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat.lt_of_le_of_lt (nat.zero_le _) (nat

done